/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'scienceTech' : IDL.Null,
  'economy' : IDL.Null,
  'history' : IDL.Null,
  'geography' : IDL.Null,
  'currentAffairs' : IDL.Null,
  'polity' : IDL.Null,
});
export const SubjectProgress = IDL.Record({
  'subject' : Subject,
  'completionPercentage' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'joinDate' : Time,
  'studyStreak' : IDL.Nat,
});
export const DailyTarget = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyTarget' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCompletedTargets' : IDL.Func([], [], []),
  'getCallerStudyProgress' : IDL.Func(
      [],
      [IDL.Vec(SubjectProgress)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTargets' : IDL.Func([], [IDL.Vec(DailyTarget)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTargetCompletion' : IDL.Func([IDL.Nat], [], []),
  'updateStudyProgress' : IDL.Func([Subject, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'scienceTech' : IDL.Null,
    'economy' : IDL.Null,
    'history' : IDL.Null,
    'geography' : IDL.Null,
    'currentAffairs' : IDL.Null,
    'polity' : IDL.Null,
  });
  const SubjectProgress = IDL.Record({
    'subject' : Subject,
    'completionPercentage' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'joinDate' : Time,
    'studyStreak' : IDL.Nat,
  });
  const DailyTarget = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyTarget' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCompletedTargets' : IDL.Func([], [], []),
    'getCallerStudyProgress' : IDL.Func(
        [],
        [IDL.Vec(SubjectProgress)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTargets' : IDL.Func([], [IDL.Vec(DailyTarget)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTargetCompletion' : IDL.Func([IDL.Nat], [], []),
    'updateStudyProgress' : IDL.Func([Subject, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };