/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RegisterUserResult = IDL.Variant({
  'ok' : IDL.Null,
  'emailTaken' : IDL.Null,
});
export const UpdateUserNameResult = IDL.Variant({
  'ok' : IDL.Null,
  'notFound' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'passwordHash' : IDL.Text }))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [RegisterUserResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserName' : IDL.Func([IDL.Text, IDL.Text], [UpdateUserNameResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RegisterUserResult = IDL.Variant({
    'ok' : IDL.Null,
    'emailTaken' : IDL.Null,
  });
  const UpdateUserNameResult = IDL.Variant({
    'ok' : IDL.Null,
    'notFound' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text, 'passwordHash' : IDL.Text }))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [RegisterUserResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserName' : IDL.Func(
        [IDL.Text, IDL.Text],
        [UpdateUserNameResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };