/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyTarget {
  'id' : bigint,
  'isCompleted' : boolean,
  'description' : string,
}
export type Subject = { 'scienceTech' : null } |
  { 'economy' : null } |
  { 'history' : null } |
  { 'geography' : null } |
  { 'currentAffairs' : null } |
  { 'polity' : null };
export interface SubjectProgress {
  'subject' : Subject,
  'completionPercentage' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'joinDate' : Time,
  'studyStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyTarget' : ActorMethod<[string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCompletedTargets' : ActorMethod<[], undefined>,
  'getCallerStudyProgress' : ActorMethod<[], Array<SubjectProgress>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTargets' : ActorMethod<[], Array<DailyTarget>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTargetCompletion' : ActorMethod<[bigint], undefined>,
  'updateStudyProgress' : ActorMethod<[Subject, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];